# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_name',
            field=models.CharField(default='Robin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_name',
            field=models.CharField(default='Kaal', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='admin', max_length=191),
            preserve_default=False,
        ),
    ]
